### Задание на повторение материала


In [1]:
import numpy as np
import pandas as pd

In [4]:
a = np.arange(12,24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [6]:
b = a.reshape(3,4)
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [8]:
c=a.reshape(4,3)
c

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [9]:
d=a.reshape(2,6)
d

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [11]:
e=a.reshape(6,2)
e

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [13]:
f=a.reshape(12,1)
f

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [14]:
f.shape

(12, 1)

In [15]:
a.shape

(12,)

In [16]:
x1=a.reshape(3,-1)
x1

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [17]:
x2=a.reshape(4,-1)
x2

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [19]:
x3=a.reshape(6,-1)
x3

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [21]:
x4=a.reshape(-1, 6)
x4

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [24]:
x5=a.reshape(-1,1)
x5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

### Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?- нет

In [44]:
b = np.random.rand(3,4)
print(b)
c=b.flatten()
print(c)
b.size

[[0.10907837 0.65373435 0.54729316 0.15688084]
 [0.7783098  0.94274201 0.83146078 0.24459912]
 [0.02730972 0.68133605 0.65951981 0.53134479]]
[0.10907837 0.65373435 0.54729316 0.15688084 0.7783098  0.94274201
 0.83146078 0.24459912 0.02730972 0.68133605 0.65951981 0.53134479]


12

In [47]:
a=np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [48]:
b=np.arange(20, 1,-2)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [68]:
a=np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [69]:
b=np.ones((3,2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [70]:
d = np.concatenate((a, b), axis=0)
d

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [72]:
a=np.arange(0,12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [73]:
A=a.reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [75]:
At=A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [78]:
B=A.dot(At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [79]:
print(np.linalg.det(B)) #Определитель равен нулю, обратнуюю матрицу не получится вычислить

0.0


In [81]:
np.random.seed(42)

In [84]:
c=np.random.randint(0, 16, 16)
c

array([11,  9,  5, 12, 11,  8,  0, 10, 10, 14,  9, 15, 11, 11, 15, 14])

In [86]:
C=c.reshape(4,4)
C

array([[11,  9,  5, 12],
       [11,  8,  0, 10],
       [10, 14,  9, 15],
       [11, 11, 15, 14]])

In [88]:
C=C*10
C

array([[1100,  900,  500, 1200],
       [1100,  800,    0, 1000],
       [1000, 1400,  900, 1500],
       [1100, 1100, 1500, 1400]])

In [89]:
D=C+B
D

array([[1105,  914,  523, 1232],
       [1114,  850,   86, 1122],
       [1023, 1486, 1049, 1712],
       [1132, 1222, 1712, 1702]])

In [90]:
d=np.linalg.det(D)
d

12670380000.00016

In [91]:
r = np.linalg.matrix_rank(D)

print(r)

4


In [109]:
D_inv = np.linalg.inv(D)

print(D_inv)

[[ 0.03195101 -0.02204647  0.00014997 -0.00874515]
 [ 0.04944646 -0.03694817  0.00461538 -0.01607739]
 [ 0.01337726 -0.01031016  0.00024957 -0.00313752]
 [-0.07020798  0.05156185 -0.00366453  0.02110312]]


In [117]:
D_inv[D_inv<0]=0
D_inv[D_inv>0]=1
D_inv

array([[1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.]])

In [134]:
ind1 = np.where(D_inv>=1)
print(ind1)

(array([0, 0, 1, 1, 2, 2, 3, 3], dtype=int64), array([0, 2, 0, 2, 0, 2, 1, 3], dtype=int64))


In [136]:
ind2=np.where(D_inv<=0)
ind2

(array([0, 0, 1, 1, 2, 2, 3, 3], dtype=int64),
 array([1, 3, 1, 3, 1, 3, 0, 2], dtype=int64))

In [137]:
E1=B[ind2,:]
E1

array([[[  5,  14,  23,  32],
        [  5,  14,  23,  32],
        [ 14,  50,  86, 122],
        [ 14,  50,  86, 122],
        [ 23,  86, 149, 212],
        [ 23,  86, 149, 212],
        [ 32, 122, 212, 302],
        [ 32, 122, 212, 302]],

       [[ 14,  50,  86, 122],
        [ 32, 122, 212, 302],
        [ 14,  50,  86, 122],
        [ 32, 122, 212, 302],
        [ 14,  50,  86, 122],
        [ 32, 122, 212, 302],
        [  5,  14,  23,  32],
        [ 23,  86, 149, 212]]])

In [138]:
E2=C[ind1,:]
E2

array([[[1100,  900,  500, 1200],
        [1100,  900,  500, 1200],
        [1100,  800,    0, 1000],
        [1100,  800,    0, 1000],
        [1000, 1400,  900, 1500],
        [1000, 1400,  900, 1500],
        [1100, 1100, 1500, 1400],
        [1100, 1100, 1500, 1400]],

       [[1100,  900,  500, 1200],
        [1000, 1400,  900, 1500],
        [1100,  900,  500, 1200],
        [1000, 1400,  900, 1500],
        [1100,  900,  500, 1200],
        [1000, 1400,  900, 1500],
        [1100,  800,    0, 1000],
        [1100, 1100, 1500, 1400]]])